[package]
name = "neon_lang"
version = "1.0.0"
edition = "2024"

[dependencies]

[[bin]]
name = "neon"
path = "src/neon.rs"

[[bin]]
name = "neocomp"
path = "src/neocomp.rs"

[[bin]]
name = "neovm"
path = "src/neovm.rs"
